[[classes.Monday]]
name = "Основы Дискретной математики"
lecturer = "Поляков Владимир Иванович"
address = "Кронверский пр., д. 49, лит. А"
classroom = "Ауд. 2337"
time_start = "09:50"
time_end = "11:20"
type = "Лекция"

[[classes.Monday]]
name = "Основы Дискретной математики"
lecturer = "Поляков Владимир Иванович"
address = "Кронверский пр., д. 49, лит. А"
classroom = "Ауд. 2337"
time_start = "11:30"
time_end = "13:00"
type = "Практика"

[[classes.Monday]]
name = "Информатика"
lecturer = "Авксентьева Елена Юрьевна"
address = "Кронверский пр., д. 49, лит. А"
classroom = "Ауд. 2305"
time_start = "13:30"
time_end = "15:00"
type = "Лабораторная"

[[classes.Monday]]
name = "Информатика"
lecturer = "Авксентьева Елена Юрьевна"
address = "Кронверский пр., д. 49, лит. А"
classroom = "Ауд. 2305"
time_start = "15:30"
time_end = "17:00"
type = "Лабораторная"

[[classes.Monday]]
name = "Основы профессиональной деятельности"
lecturer = "Остапенко Ольга Денисовна"
address = "Кронверский пр., д. 49, лит. А"
classroom = "Ауд. 1338"
time_start = "17:10"
time_end = "18:40"
type = "Лабораторная"

[[classes.Thursday]]
name = "Россия в истории современных международных отношений"
lecturer = "Кутлубаева Дария Нуровна"
address = "Кронверский пр., д. 49, лит. А"
classroom = "Ауд. 2308"
time_start = "13:30"
time_end = "15:00"
type = "Практика"

[[classes.Thursday]]
name = "Россия в истории современных международных отношений"
lecturer = "Богомазов Николай Иванович"
address = "Кронверский пр., д. 49, лит. А"
classroom = "Ауд. 1419"
time_start = "15:30"
time_end = "17:00"
type = "Лекция"
